version: '3'
services:
  microservice:
    image: valdergallo.microservice.flask:{$ENVIRONMENT}
    build: .
    restart: always
    container_name: microservice
    ports:
      - "5000:5000"
    networks:
      - webnet
    volumes:
      - pipstorage:/root/.cache/pip
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main:start_server
      - DEBUG=True
      - APP_SETTINGS=Develop
      - SQLALCHEMY_ECHO=True
      - PORT=5000
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/

volumes:
    pipstorage:

networks:
  webnet:
