"""empty message

Revision ID: 8885d8eeed8c
Revises: 1c50e03482cf
Create Date: 2020-12-12 22:19:50.643931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8885d8eeed8c'
down_revision = '1c50e03482cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_code', table_name='inventory')
    op.create_index(op.f('ix_inventory_code'), 'inventory', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_code'), table_name='inventory')
    op.create_index('ix_inventory_code', 'inventory', ['code'], unique=False)
    # ### end Alembic commands ###
